### ISSUE TITLE
support named "profiles"

### ISSUE THREAD

**Issue by ahl** [oxidecomputer/oxide.rs#6]
The CLI should have a config file that lets users set up profiles with user-selected names. This would allow use like this `oxide --profile silo-arcturus instance create ...`

**Comment by karencfv** [comment]
Related to https://github.com/oxidecomputer/oxide-sdk-rust/issues/39

In the discussions from that issue, we came to the conclusion that the best way forward would be to have a `config` file that has settings for each profile like this:

```toml
default = "my-profile"

[my-profile]
host = "https://instance1.customer.com"
# Only needed to disambiguate in the case that multi user is wanted. Optional in single user case
user_id = "f0ce3dcb-fc8c-4e34-aca9-ba3f3fd3d5b6"
# project here is optional
project = "my-project"

# Repeated as needed
```

The `hosts.toml` file should be renamed `credentials` to be more specific of it's purpose. For now we will keep this simple, and keep the same format we currently have. This file will use the host as the key. In the future we may want to add fields like `token_expiry_date` and other useful information.

```toml
["http://127.0.0.1:12220/"]
token = "oxide-token-1111111111111111111111111111111"
user = "001de000-05e4-4000-8000-000000004007"
```

As for override hierarchy it should be as follows:

- Persistent default specification in the configuration file `oxide config set default my-profile`.
- If set, prefer an environment variable `OXIDE_PROFILE=my-silo` over the default.
- If provided, prefer a command-line argument `oxide --profile my-other-silo` over the environment or the default.

Lastly, to make the usage of these files clearer, there should be an `oxide init` command that walks the user through initial set up. This command will have the ability to be interactive or do the initialisation through flags. It will take the user through setting each of the fields (or leaving blank to keep defaults) and setting a default host (this command will require the user to log in before starting the init process).
